name: release build
on: 
  push:
    branches: ['release']
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: build bot
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        script: | 
          cd DotnetDiscordBot
          git pull
          docker compose --env-file ./.env up -d
